export enum FriendActionType {

    // ADD_CIRCLE = 'ADD_CIRCLE',
    // DELETE_CIRCLE = 'DELETE_CIRCLE',
    // UPDATE_CIRCLE = 'UPDATE_CIRCLE',
    // ADD_LIST_CIRCLE = 'ADD_LIST_CIRCLE',
    CLEAR_ALL = 'CLEAR_ALL',
    // OPEN_CIRCLE_SETTINGS = 'OPEN_CIRCLE_SETTINGS',
    // CLOSE_CIRCLE_SETTINGS = 'CLOSE_CIRCLE_SETTINGS',
    // ADD_FOLLOWING_FRIEND = 'ADD_FOLLOWING_FRIEND',
    // DELETE_FOLLOWING_FRIEND = 'DELETE_FOLLOWING_FRIEND',
    // UPDATE_FRIEND_TIE = 'UPDATE_FRIEND_TIE',
    ADD_FRIEND_TIE_LIST = 'ADD_FRIEND_TIE_LIST',
    ADD_FRIEND_REQUEST_LIST = 'ADD_FRIEND_REQUEST_LIST',
    ADD_ALL_USERS_LIST = 'ADD_ALL_USERS_LIST',
    // ADD_FRIEND_TIED_LIST = 'ADD_FRIEND_TIED_LIST',
    // DELETE_FRIEND_FROM_CIRCLE = 'DELETE_FRIEND_FROM_CIRCLE',
    // SHOW_SELECT_CIRCLE_BOX = 'SHOW_SELECT_CIRCLE_BOX',
    // HIDE_SELECT_CIRCLE_BOX = 'HIDE_SELECT_CIRCLE_BOX',
    // SET_SELECTED_CIRCLES_FRIEND_BOX_COMPONENT = 'SET_SELECTED_CIRCLES_FRIEND_BOX_COMPONENT',
    // REMOVE_SELECTED_CIRCLES_FRIEND_BOX_COMPONENT = 'REMOVE_SELECTED_CIRCLES_FRIEND_BOX_COMPONENT',
    // OPEN_SELECT_CIRCLES_FRIEND_BOX_COMPONENT = 'OPEN_SELECT_CIRCLES_FRIEND_BOX_COMPONENT',
    // CLOSE_SELECT_CIRCLES_FRIEND_BOX_COMPONENT = 'CLOSE_SELECT_CIRCLES_FRIEND_BOX_COMPONENT',
    // SHOW_FOLLOWING_FRIEND_LOADING = 'SHOW_FOLLOWING_FRIEND_LOADING',
    // HIDE_FOLLOWING_FRIEND_LOADING = 'HIDE_FOLLOWING_FRIEND_LOADING'

}
